@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyWordBank <<Interface>>
Interface Model <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface ObservableList <<Interface>>
Class WordBank
Class ModelManager
Class UserPrefs

Package Deck {
Package Entry {
Class Entry
Class Translation
Class UniqueEntryList
Class Word
}
Class Deck
Class DeckName
Class UniqueDeckList
}

Package Play {
Package Scoring {
Class BinaryScoring
Class QuestionAttempt
Class QuizAttempt
Interface Scoring <<Interface>>
}
Class Leitner
Class Score
}


Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModelManager ..up|> Model
ModelManager o-->"1" WordBank
Model .> ObservableList
ModelManager *->"1" UserPrefs
UserPrefs .|> ReadOnlyUserPrefs

UniqueEntryList o->"*" Entry
Entry *-->"1" Word
Entry *-->"1" Translation

UniqueDeckList o-->"*" Deck
Deck *-->"1" DeckName
Deck *-->"1" UniqueEntryList

BinaryScoring ..up|> Scoring
QuizAttempt *--> Score
QuizAttempt *->"*" QuestionAttempt
QuizAttempt ..>"1" Scoring
QuestionAttempt *->"1" Score

Score --up[hidden]> Leitner

UniqueDeckList -[hidden]> UniqueEntryList

WordBank .|> ReadOnlyWordBank
WordBank *--->"1" UniqueEntryList
WordBank *-->"1" UniqueDeckList
WordBank -> Entry: has filtered list of

ModelManager *--->"0..1" Leitner
ModelManager *-->"0..1" QuizAttempt
ModelManager -> Deck: has filtered list of


@enduml
