@startuml
start
:User executes select command;
if() then ([Logic Manager is in Play Mode])
:Command is treated as an Answer Command;
else([Logic Manager is not in Play Mode])
if() then([Command is in the correct format])
if() then([Index is valid])
:Update selected deck in ModelManager;
:Switch the current tab on the UI to the Entries tab;
:Display entries of the selected deck on the Entries tab (if any);
else([Index is not valid])
:Display an error message to the result box of the UI indicating that the index is not valid;
endif
else([Command is not in the correct format])
:Display an error message to the result box of the UI indicating that the command is not in the right format;
endif
endif
stop
@enduml
