@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

Interface Storage <<Interface>>
Interface UserPrefsStorage <<Interface>>
Interface WordBankStorage <<Interface>>

Class StorageManager
Class JsonUserPrefsStorage
Class JsonWordBankStorage

StorageManager .up.|> Storage
StorageManager o--> WordBankStorage
StorageManager o--> UserPrefsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonWordBankStorage .up.|> WordBankStorage
JsonWordBankStorage .down.> JsonSerializableWordBankStorage

JsonSerializableWordBankStorage ..> JsonAdaptedDeck

JsonAdaptedDeck ..> JsonAdaptedEntry
JsonAdaptedDeck ..> JsonQuizAttempt

JsonAdaptedEntry ..> JsonAdaptedWord
JsonAdaptedEntry ..> JsonAdaptedTranslation

JsonQuizAttempt ..> JsonAdaptedQuestionAttempt
JsonQuizAttempt ..> JsonAdaptedScore
@enduml
