@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":WordBankParser" as WordBankParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedWordBank" as VersionedWordBank MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> WordBankParser : parseCommand(undo)
activate WordBankParser

create UndoCommand
WordBankParser -> UndoCommand
activate UndoCommand

UndoCommand --> WordBankParser
deactivate UndoCommand

WordBankParser --> LogicManager : u
deactivate WordBankParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoWordBank()
activate Model

Model -> VersionedWordBank : undo()
activate VersionedWordBank

VersionedWordBank -> VersionedWordBank :resetData(ReadOnlyWordBank)
VersionedWordBank --> Model :
deactivate VersionedWordBank

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
